### ISSUE TITLE
Boostrap portfolio setup

### ISSUE THREAD

**Issue by ehs9nino** [kamzzy/portfolioSetupWithBS#4]
The portfolio project using bootstrap was written well. We can suggest some minor recommendations that will make the whole portfolio look better.

The social icons on the bottom of the page need some padding according to the given Figma design and we think with the bootstrap you can manage the padding of that section. 
Please go through this link https://getbootstrap.com/docs/5.0/getting-started/introduction/  and you can find how it works.

**Comment by preciousakams** [comment]
Thanks for the feedback, i will go through the link
